# Generated by Django 5.1.5 on 2025-02-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
