# Generated by Django 5.1.5 on 2025-02-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerCategory',
            fields=[
                ('cat_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('category_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_trainer_cat',
            },
        ),
    ]
