# Generated by Django 5.1.5 on 2025-02-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trainercategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='tbl_login',
        ),
    ]
