# Generated by Django 5.1.5 on 2025-02-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_login_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(max_length=20)),
                ('trainer_age', models.IntegerField()),
                ('trainer_email', models.EmailField(max_length=50, unique=True)),
                ('trainer_expertise', models.CharField(max_length=50)),
                ('trainer_status', models.BooleanField(default=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainercategory')),
            ],
            options={
                'db_table': 'tbl_trainer',
            },
        ),
    ]
