# Generated by Django 5.1.5 on 2025-02-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('workout_names', models.CharField(max_length=50)),
                ('intensity', models.CharField(max_length=10)),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainer')),
            ],
            options={
                'db_table': 'tbl_workout',
            },
        ),
    ]
