# Generated by Django 5.1.5 on 2025-02-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('time_slot', models.TimeField()),
                ('session_status', models.BooleanField(default=True)),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainer')),
            ],
            options={
                'db_table': 'tbl_session',
            },
        ),
    ]
