# Generated by Django 5.1.5 on 2025-02-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainercategory',
            name='category_payment',
            field=models.IntegerField(default=0),
        ),
    ]
