# Generated by Django 5.1.5 on 2025-02-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_trainercategory_category_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=50, unique=True)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=50)),
                ('card_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('card_expiry', models.DateField()),
                ('last_payment_date', models.DateField()),
                ('cat_id', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='main.trainercategory')),
            ],
            options={
                'db_table': 'tbl_customer',
            },
        ),
    ]
