# Generated by Django 5.1.5 on 2025-02-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customer_customer_id_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.BooleanField(default=True),
        ),
    ]
