# Generated by Django 5.1.5 on 2025-02-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customer_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('muscle_mass', models.IntegerField()),
                ('fat_mass', models.IntegerField()),
                ('date', models.DateField()),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'tbl_assessment',
            },
        ),
    ]
