# Generated by Django 5.1.5 on 2025-02-14 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('session_id', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='main.session')),
            ],
            options={
                'db_table': 'tbl_booking',
            },
        ),
    ]
