# Generated by Django 5.1.5 on 2025-02-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_booking_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_status',
        ),
    ]
