# Generated by Django 5.1.5 on 2025-02-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_booking_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('food_plan', models.TextField()),
                ('goal', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('workout_id', models.ForeignKey(db_column='workout_id', on_delete=django.db.models.deletion.CASCADE, to='main.workout')),
            ],
            options={
                'db_table': 'tbl_records',
            },
        ),
    ]
