# Generated by Django 5.1.5 on 2025-02-15 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('change_summary', models.TextField()),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assessment')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.record')),
            ],
            options={
                'db_table': 'tbl_analytics',
            },
        ),
    ]
