# Generated by Django 5.1.5 on 2025-03-20 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
