# Generated by Django 5.1.5 on 2025-06-18 05:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_customer_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('plan_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('goal', models.CharField(choices=[('bulk', 'Bulk'), ('cut', 'Cut'), ('maintenance', 'Maintenance')], max_length=20)),
                ('week_start_date', models.DateField()),
                ('workout_split', models.CharField(max_length=50)),
                ('day_exercises', models.JSONField()),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'tbl_workout_plan',
            },
        ),
        migrations.CreateModel(
            name='ExerciseWeight',
            fields=[
                ('weight_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=50)),
                ('set_1_weight', models.FloatField(blank=True, null=True)),
                ('set_2_weight', models.FloatField(blank=True, null=True)),
                ('set_3_weight', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'tbl_exercise_weight',
                'unique_together': {('customer_id', 'exercise_name')},
            },
        ),
    ]
