# Generated by Django 5.1.5 on 2025-06-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_workoutplan_exerciseweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='trainer_id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='workout_id',
        ),
        migrations.RenameField(
            model_name='exerciseweight',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='day_exercises',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='fri_exercises',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='mon_exercises',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='sat_exercises',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='sun_exercises',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='thu_exercises',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='tue_exercises',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='wed_exercises',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, to='main.trainer')),
            ],
            options={
                'db_table': 'tbl_exercise',
            },
        ),
        migrations.AlterUniqueTogether(
            name='exerciseweight',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exerciseweight',
            name='exercise',
            field=models.ForeignKey(blank=True, db_column='exercise_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exercise'),
        ),
        migrations.AddField(
            model_name='record',
            name='exercise',
            field=models.ForeignKey(blank=True, db_column='exercise_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exercise'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseweight',
            unique_together={('customer', 'exercise', 'date')},
        ),
        migrations.DeleteModel(
            name='Analytics',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.RemoveField(
            model_name='exerciseweight',
            name='exercise_name',
        ),
    ]
