# Generated by Django 5.1.5 on 2025-06-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_workout_trainer_id_remove_record_workout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
