# Generated by Django 5.1.5 on 2025-06-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_exercise_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseweight',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
