# Generated by Django 5.1.5 on 2025-06-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_exerciseweight_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='assessment',
            field=models.ForeignKey(blank=True, db_column='assessment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.assessment'),
        ),
    ]
