# Generated by Django 5.1.5 on 2025-06-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_workoutplan_assessment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutplan',
            unique_together={('customer', 'assessment')},
        ),
    ]
