# Generated by Django 5.1.5 on 2025-06-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_workoutplan_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='fri_exercises',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='mon_exercises',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='sat_exercises',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='sun_exercises',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='thu_exercises',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='tue_exercises',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='wed_exercises',
            field=models.TextField(blank=True, null=True),
        ),
    ]
