# Generated by Django 5.1.5 on 2025-06-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_workoutplan_fri_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseweight',
            name='id',
            field=models.BigAutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciseweight',
            name='weight_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
