# Generated by Django 5.1.5 on 2025-06-19 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_exerciseweight_id_alter_exerciseweight_weight_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseweight',
            name='id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='exercise',
        ),
        migrations.AddField(
            model_name='record',
            name='plan_id',
            field=models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workoutplan'),
        ),
        migrations.AlterField(
            model_name='exerciseweight',
            name='weight_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
