# Generated by Django 5.1.5 on 2025-06-19 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_exerciseweight_id_remove_record_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='food_plan',
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('diet_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('calories', models.IntegerField()),
                ('protein_grams', models.IntegerField()),
                ('fat_grams', models.IntegerField()),
                ('carb_grams', models.IntegerField()),
                ('water_liters', models.FloatField()),
                ('week_start_date', models.DateField()),
                ('assessment', models.ForeignKey(blank=True, db_column='assessment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.assessment')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'tbl_diet',
                'unique_together': {('customer', 'assessment')},
            },
        ),
        migrations.AddField(
            model_name='record',
            name='diet_id',
            field=models.ForeignKey(blank=True, db_column='diet_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.diet'),
        ),
    ]
