# Generated by Django 5.1.5 on 2025-06-19 16:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_record_food_plan_diet_record_diet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('intake_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('calories', models.IntegerField(default=0)),
                ('protein_grams', models.IntegerField(default=0)),
                ('fat_grams', models.IntegerField(default=0)),
                ('carb_grams', models.IntegerField(default=0)),
                ('water_liters', models.FloatField(default=0)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'tbl_intake',
                'unique_together': {('customer', 'date')},
            },
        ),
    ]
