# Generated by Django 5.1.5 on 2025-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_intake_intake_id_alter_intake_protein_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='intake_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intake',
            name='protein_grams',
            field=models.IntegerField(default=0),
        ),
    ]
